-
  In order to test the choice of a cancel reason when canceling a sale order
  I create a new cancel reason
-
  !record {model: sale.order.cancel.reason, id: cancel_reason_test}:
    name: Canceled for tests
-
  Given I create a sale order
-
  !record {model: sale.order, id: sale_order_cancel_01}:
    partner_id: base.res_partner_2
    order_line:
      - product_id: product.product_product_7
        product_uom_qty: 8
-
  When I cancel it with the wizard asking for the reason
-
  !python {model: sale.order.cancel}: |
    context = {'active_model': 'sale.order',
               'active_ids': [ref('sale_order_cancel_01')],
               }
    reason_id = ref('cancel_reason_test')
    wizard_id = self.create(cr, uid,
                            {'reason_id': reason_id},
                            context=context)
    self.confirm_cancel(cr, uid, wizard_id, context=context)
-
  Then the sale order should be canceled
  and the reason stored
-
  !assert {model: sale.order, id: sale_order_cancel_01, string: the sale order should be canceled}:
    - state == 'cancel'
    - cancel_reason_id.id == ref('cancel_reason_test')
